spring:
  application:
    name: vuege
  
  # Database Configuration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/vuege
    username: postgres
    password: postgres
  
  # Liquibase Configuration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  
  # GraphQL Configuration
  graphql:
    graphiql:
      enabled: false
    schema:
      locations: classpath:graphql/
    path: /api/graphql

# JWT Configuration
app:
  jwt:
    secret: vuege-super-secret-jwt-key-for-production-use-change-in-production
    expiration: 86400000 # 24 часа в миллисекундах

# Server Configuration
server:
  port: 8082

# Logging Configuration
logging:
  level:
    io.github.bondalen: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.liquibase: DEBUG
    org.springframework.security: DEBUG
    liquibase: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: backend.log
    max-size: 10MB
    max-history: 30

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops,beans,threaddump,heapdump
      base-path: /actuator
      discovery:
        enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
    metrics:
      enabled: true
  health:
    r2dbc:
      enabled: true
    db:
      enabled: true
    mail:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true

  # Security Configuration for Actuator
  security:
    user:
      name: admin
      password: admin123
    basic:
      enabled: false