@startuml Migration Process Flow

start

#lightgreen:Создание задачи миграции;

partition "Перенос таблиц" {
    :Выполнение процесса переноса таблиц;
    note right: Детализация в отдельной диаграмме
}

:Генерация отчета;
:Анализ результатов;
stop

@enduml