@startuml Table Migration Detailed Process

start

#lightgreen:Создание запроса для получения списка таблиц исходной БД;

#lightgreen:Заполнение системы контроля данными о исходныхтаблицах;
note right: INSERT INTO mcl.mssql_tables

#lightgreen:Заполнение системы контроля данными о исходных типах данных;
note right: таблицы базовых и производных типов данных

partition "Заполнение системы контроля данными о полях исходных таблиц" {
    #lightgreen:Заполнение системы контроля данными о полях исходных таблиц;
    note right: Детализация в отдельной диаграмме
}

#lightgreen:Оптимизация поля описаний колонок;
note right: Переименование readable_description в column_description

:Определение аналогов Postgres для исходных типов данных;
note right: таблицы базовых и производных типов Postgres

stop

@enduml