@startuml Table Migration Transfer

start

:Фильтрацией отбираем не завершенные таблицы;

if(не завершенные таблицы имеются?) then(да)

:Сортировка незавершенных таблиц в таблице целевых таблиц по алфавиту;

:Выбираем первую не завершенную таблицу по алфавиту;

repeat

    if(таблица имеет внешние ключи?) then(да)

        if(таблицы на которые ссылаются внешние ключи имеются?) then(да)

        else(нет)

        endif

    else(нет)
 
        :Создаём таблицу в целевой БД;

        :Переносим данные из исходной таблицы в целевую таблицу;

        :Устанавливаем статус завершения таблицы;

   endif
 
  :Переходим к следующей не завершенной таблице;

repeat while (следующая не завершенная таблица имеется?) is (да) not (нет)

else(нет)

endif

:Таблицы перенесены;

stop
@enduml